#********************* USAGE ********************* #
# When load a module use cfg.module as its initializor
# eg: classifier_pipeline : Classifier(cfg.classifier_cfg)
# All functions are based on OmegaConf
# OmegaConf provides the Interpolation Function ${}
# ************************************************ #

# ******************** Train Settings ******************** #

project: "D4A_Diffusion with Agumented Attention Adversarial Attack"
exp_name: "Entity-Patch-Exp"
model_arch: "UNet++"
diffusion_arch: "L-MAG"

debug: True

epochs             : 30
lr                 : 0.01 #05
ignore_label       : 255
batch_size         : 2
num_workers        : 4
patch_size         : 256
crop_sizeHW        : [1024, 1024]
log_iter           : 200
gradient_storage   : 20

hyper_params :
  # Loss Control
  classifier_loss_weight : 1
  cross_loss_weight: 5e7 # legacy version
  self_loss_weight : 1
  cross_ip_loss_weight : 1e4
  cross_txt_loss_weight: 1e3
  # Classifier: outer enhancement
  outer_enhancement : True
  outer_enhan_patch_supress_weight : 0.8
  # ImageNet Normalize
  mean : [0.485, 0.456, 0.406]
  std  : [0.229, 0.224, 0.225]
  # patch
  patch_alpha : 0.25  # lower alpha means lower visibility
  # diffusion
  intermediate_steps : 3
  RFES_edge : 16 # 0 16 32 or more.

paths :
  patch_load_from : ""
  dataset_base_addr : "/home/atman/home/D4A/data/rellis3d"
  model_pretrained : "/home/atman/home/D4A/src/configs/pretrained/UNet++_rellis_50e_512x512.pth"
  diffusion_model_path: "runwayml/stable-diffusion-v1-5"
  IP_Adapter_path: "h94/IP-Adapter"

metrics_cfg:
  # MulticlassJaccardIndex and MAcc(ASR)
  num_classes: 19
  average: "weighted" # No "macro" bro
  ignore_index: ${ignore_label}
  # LPIPS
  lpips_net: "alex"

dataset_cfg:
  ignore_label: ${ignore_label}
  crop_sizeHW: ${crop_sizeHW}
  base_addr: ${paths.dataset_base_addr}
  mode: train # train test val

dataloader_cfg :
  shuffle: True
  batch_size: ${batch_size}
  num_workers: ${num_workers}

classifier_cfg :
  # model
  model: "UnetPlusPlus"
  argv:
    encoder_name     : "resnet34"
    encoder_weights  : "imagenet"
    in_channels      : 3
    classes          : 19
  load_from : ${paths.model_pretrained}
  # basic settings
  ignore_label : ${ignore_label}
  patch_size : ${patch_size}
  outer_enhance : ${hyper_params.outer_enhancement}
  patch_supress_weight : ${hyper_params.outer_enhan_patch_supress_weight}
  loss_weight : ${hyper_params.classifier_loss_weight}
  mean    : ${hyper_params.mean} # ImageNet Pretrained RGB
  std     : ${hyper_params.std}
  # preprocessor


  # This version only support RGB 3 ch Patch
  # with FIXED transparency as hyperparameter

patch_handler_cfg :
  # optim settings: self.optim_
  lr : ${lr}
  batch_size : ${batch_size}
  optim_name : "Adam"
  # Patch geometry
  load_from : ${paths.patch_load_from}
  patch_size : ${patch_size}
  ignore_label: ${ignore_label}
  location : "random"
  # 0.05 patch + (1-005) Img
  alpha : ${hyper_params.patch_alpha}
  enable_eot : True
  rot_deg : 20
  scale : [0.8, 1.2]
  max_translate : 0.05

LMAG_cfg:
  debug: ${debug}
  diffusion_model_path: ${paths.diffusion_model_path}
  IP_Adapter_path: ${paths.IP_Adapter_path}
  rfes_edge: ${hyper_params.RFES_edge}
  # Basic settings
  resolution: ${eval:'${patch_size} + 2 * ${hyper_params.RFES_edge}'}
  img_height: ${eval:'${patch_size} + 2 * ${hyper_params.RFES_edge}'}
  img_width: ${eval:'${patch_size} + 2 * ${hyper_params.RFES_edge}'}
  # Sensitiveness
  timestep: 200
  # extract map stratgy
  target_downscale: 16
  self_pca_start: 0
  self_pca_layers: 4
  # criterions
  self_criterion: "CosineSimilarity"
  self_criterion_kwargs:
    dim: -1
