#********************* USAGE ********************* #
# When load a module use cfg.module as its initializor
# eg: classifier_pipeline : Classifier(cfg.classifier_cfg)
# All functions are based on OmegaConf
# OmegaConf provides the Interpolation Function ${}
# ************************************************ #

# ******************** Train Settings ******************** #

project: "Rellis3D-Adversarial-Attack"
exp_name: "Entity-Patch-Exp"
model_arch: "UNet++"

epochs             : 30
lr                 : 0.005
ignore_label       : 255
batch_size         : 4
num_workers        : 4
patch_size         : 128
crop_sizeHW        : [512, 512]
log_iter           : 100
gradient_storage   : 50

hyper_params :
  # Loss Control
  classifier_loss_weight : 1
  self_loss_weight : 5e7
  cross_loss_weight : 5e7
  # Classifier: outer enhancement
  outer_enhancement : True
  outer_enhan_patch_supress_weight : 0.8
  # ImageNet Normalize
  mean : [0.485, 0.456, 0.406]
  std  : [0.229, 0.224, 0.225]
  # patch
  patch_alpha : 0.1  # lower alpha means lower visibility
  # diffusion
  intermediate_steps : 1
  RFES_edge : 16 # 0 16 32 or more.

paths :
  patch_load_from : ""
  dataset_base_addr : "/home/atman/home/patch_attack_public/data/rellis3d"
  model_pretrained : "/home/atman/home/patch_attack_public/src/configs/pretrained/UNet++_rellis_50e_512x512.pth"

metrics_cfg:
  # MulticlassJaccardIndex and MAcc(ASR)
  num_classes: 19
  average: "weighted" # No "macro" bro
  ignore_index: ${ignore_label}
  # LPIPS
  lpips_net: "alex"

dataset_cfg:
  ignore_label: ${ignore_label}
  crop_sizeHW: ${crop_sizeHW}
  base_addr: ${paths.dataset_base_addr}
  mode: train # train test val

dataloader_cfg :
  shuffle: False
  batch_size: ${batch_size}
  num_workers: ${num_workers}

classifier_cfg :
  # model
  model: "UnetPlusPlus"
  argv:
    encoder_name     : "resnet34"
    encoder_weights  : "imagenet"
    in_channels      : 3
    classes          : 19
  load_from : ${paths.model_pretrained}
  # basic settings
  ignore_label : ${ignore_label}
  patch_size : ${patch_size}
  outer_enhance : ${hyper_params.outer_enhancement}
  patch_supress_weight : ${hyper_params.outer_enhan_patch_supress_weight}
  loss_weight : ${hyper_params.classifier_loss_weight}
  mean    : ${hyper_params.mean} # ImageNet Pretrained RGB
  std     : ${hyper_params.std}
  # preprocessor


  # This version only support RGB 3 ch Patch
  # with FIXED transparency as hyperparameter

patch_handler_cfg :
  # optim settings: self.optim_
  lr : ${lr}
  batch_size : ${batch_size}
  optim_name : "Adam"
  # Patch geometry
  load_from : ${paths.patch_load_from}
  patch_size : ${patch_size}
  ignore_label: ${ignore_label}
  location : "center"
  # 0.05 patch + (1-005) Img
  alpha : ${hyper_params.patch_alpha}
  enable_eot : True
  rot_deg : 20
  scale : [0.8, 1.2]
  max_translate : 0.05

diffusion_cfg :
  batch_size_of_diffusion: 1 # 每次输入单张图进入Pipeline
  diffusion_resolution: ${patch_size}
  num_inference_steps: 50
  guidance_scale: 4.5
  intermediate_steps: ${hyper_params.intermediate_steps} # 中介步骤，从潜空间回来一共去噪几次
  self_weight : ${hyper_params.self_loss_weight}
  cross_weight : ${hyper_params.cross_loss_weight}
  RFES_edge : ${hyper_params.RFES_edge}
  # 为提示词服务的字典。可以增加一些描述，不过也可以不增加
  label_dict :
    0: "dirt"
    1: "green grass land"
    2: "tree"
    3: "pole"
    4: "water"
    5: "blue sky and shallow clouds on the top"
    6: "vehicle"
    7: "object"
    8: "asphalt"
    9: "building"
    10: "log"
    11: "person"
    12: "fence"
    13: "bush"
    14: "concrete"
    15: "barrier"
    16: "puddle"
    17: "mud"
    18: "rubble"
